name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: salim963/mmywebshopbackend:${{github.run_number}},
      # Install caprover cli
      - name: install caprover cli
        run: npm install -g caprover
      # Trigger deploy on Caprover instance
      - name: Deploy app
        env: 
          APP_NAME: 'backend-webshop'
          APP_URL: 'https://admin.samat.diplomportal.dk/'
          IMAGE_NAME: 'salim963/mmywebshopbackend:${{github.run_number}}'
        run: 
         'caprover deploy --caproverUrl=$APP_URL --caproverPassword=${{ secrets.CAPROVER_PASSWORD }} --imageName=$IMAGE_NAME --appName=$APP_NAME'
      
